
default: &default
  adapter: sqlserver
  encoding: utf8
  username: sa
  password: <%= ENV['SA_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: ss_app_development

test:
  <<: *default
  database: ss_app_test

